name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: 'latest'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}


      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy-pages-preview.outputs.deployment-url }}
          STORYBOOK_DEPLOYMENT_URL: ${{ steps.deploy-storybook-preview.outputs.deployment-url }}
          STORYBOOK_BRANCH_URL: ${{ steps.deploy-storybook-preview.outputs.deployment-alias-url }}
        run: |
          echo $DEPLOYMENT_URL
          echo $STORYBOOK_DEPLOYMENT_URL
          echo $STORYBOOK_BRANCH_URL

      - name: Create comment file
        id: create-comment-file
        env:
          DEPLOYMENT_URL: ${{ steps.deploy-pages-preview.outputs.deployment-url }}
          STORYBOOK_DEPLOYMENT_URL: ${{ steps.deploy-storybook-preview.outputs.deployment-url }}
          STORYBOOK_BRANCH_URL: ${{ steps.deploy-storybook-preview.outputs.deployment-alias-url }}
        run: |
          cat  << EOF > comment.md
          ## ðŸš€ Deploying ${{ github.event.repository.name }} with Cloudflare Workers
          <table>
            <tr>
              <th scope="row">Preview URL</th>
              <td><a href="$DEPLOYMENT_URL" target="_blank" rel="noopener noreferrer">$DEPLOYMENT_URL</a></td>
            </tr>
            <tr>
              <th scope="row">Storybook Preview URL</th>
              <td><a href="$STORYBOOK_DEPLOYMENT_URL" target="_blank" rel="noopener noreferrer">$STORYBOOK_DEPLOYMENT_URL</a></td>
            </tr>
            <tr>
              <th scope="row">Storybook branch URL</th>
              <td><a href="$STORYBOOK_BRANCH_URL" target="_blank" rel="noopener noreferrer">$STORYBOOK_BRANCH_URL</a></td>
            </tr>
          </table>
          EOF

      - name: Create PR comment
        if: ${{ steps.deploy-pages-preview.outcome == 'success' && steps.deploy-storybook-preview.outcome == 'success' }}
        run: gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}